### ISSUE TITLE
Cosine distribution

### ISSUE THREAD

**Issue by kennyalive** [aras-p/ToyPathTracer#2]
Hi Aras, 

For lambertian scattering we have this line:
float3 target = rec.pos + rec.normal + RandomInUnitSphere();
and then we normalize target

The result of RandomInUnitSphere() should also be normalized, otherwise we won't get cosine distribution for target direction.  I believe Peter Shirley mentioned about potential bug in the image generation in the third book, it could be because of this.

**Comment by aras-p** [comment]
Thanks, will look at it!

I also have a double-lighting problem due to direct light sampling, will fix with next blog post :)

**Comment by aras-p** [comment]
Fixed!

**Comment by vchizhov** [comment]
This may still be correct. According to: http://amietia.com/lambertnotangent.html
sampling a point inside the unit ball is equivalent to sampling a cosine weighted hemisphere. The lack of normalization (pdf = cos(theta)/PI) accounts for the cosine due to Lambert's law in the rendering equation (the idea is that these cancel out). The only term it doesn't account for is the PI, which means that our diffuse albedo can be regarded as premultiplied with 1/PI (then one has to be careful regarding energy conserving values).

**Comment by vchizhov** [comment]
Here is an informal derivation in the 2d case. A circle with radius 1 centered at (0,1) is given by r = 2*sin(theta), theta in [0, pi] in polar coordinates. (To see this, define the ray x = t * cos(theta), y = t * sin(theta), and find the intersection with x^2 + (y-1)^2 = 1. One gets x = 2 * cos(theta) * sin(theta) and y = 2 * sin(theta)^2, then r = |x-y| = 2 * |sin(theta)|). If we instead use theta in [-pi/2, pi/2] (as is customary in CG), one gets r = 2 * cos(theta). Since the points are uniformly distributed the unnormalized probability of sampling direction theta is 2 * cos(theta), the normalized pdf is cos(theta)/4. The only difference with the cosine weighted hemispherical pdf is a constant factor of 2.

**Comment by vchizhov** [comment]
Turns out neither points distributed in the offset unit ball, nor on the offset unit sphere induce a cosine distribution.
I did a full derivation of the induced probabilities, you can find it here: https://github.com/vchizhov/Derivations/blob/master/Probability%20density%20functions%20on%20normalized%20S%20and%20dS.pdf. Points distributed uniformly in the offset ball and then normalized produce a cos^3 distribution on the upper unit hemisphere, so I was incorrect on that account. However, points distributed uniformly on the offset unit sphere that are normalized produce a cos^2 distribution, so even that is wrong. Your best bet is probably just directly generating cosine distributed points on the unit hemisphere and using the code from here: http://jcgt.org/published/0006/01/01/ to align it with the normal.
